### PR TITLE
web: leaderboard

### LINKED ISSUE #46: Generate simple HTML page with game statistics/leaderboard

### PR DESCRIPTION
**Pull request by SveaGaenzle**
I have tried to create a basic leaderboard for the web.

## Issue:

- resolves #46

## Description:
- I added `getAllUsers` and `getRankedUsers`  to the `sqlite.data` file.
- `getAllUsers`  returns all users from the database
- `getRankedUsers` ranks all users according to the highest `mu-sigma` value.
- I have added the file `_dashboard.leaderboard.tsx` to display the leaderboard.
- I have added to the `Leaderboard` in the `Loader` that the array with the ranked users and the logged-in user is loaded. The ranked users and the username of the logged-in user are returned.
- The `Leaderboard`dislays a table (the leaderboad). The table has the columns _Ranking_ and _User_ and is filled with the array _users_. The row corresponding to the logged-in user is colored blue. 
- The leaderboard can display either 5, 10, 25 or all users. You can switch between the individual pages using buttons.

## TODO:
- [x] Show the rank on Home

### CODE REVIEW

**Comment by PacoSchatz** [comment]
Thanks for your work. And good, that you changed it to sort the users now by the lower confidence bound. In my browser it looks great.

When testing it in Firefox emulating a mobile phone the table is still quite wide. This is no dealbreaker for me but neither it's perfect.
grafik
grafik

**Comment by SveaGaenzle** [comment]
I have tried to implement your suggestion. 
You can now see the ranking and the usernames at the same time. 
However, I did not get the navigation bar smaller, which is why you still have to scroll, wehn you whant to switch pages.
grafik
grafik

**Comment by PacoSchatz** [comment]
nice change. I definitely like this layout much more 👍

**Review by Cari1111 — APPROVED** [review]
Thanks for the implementation of the leaderboard. I tested all the new features and everything works correctly.

**Pull request merged**
